version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - importas
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - varnamelen
    - wsl
  settings:
    govet:
      disable:
        - printf
    staticcheck:
      checks:
        - all
    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - wg sync.WaitGroup
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - gochecknoinits
        path: main\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
